### PR TITLE
3046016 Route patterns

### PR DESCRIPTION
**Pull request by safalliajoseph**
d.o issue: https://www.drupal.org/project/3034968/issues/3046016

### CODE REVIEW

**Comment by safalliajoseph** [comment]
Hey @krystalcode , I have closed https://github.com/shabananavas/elastic_apm/pull/20 as it had un-related histories. I have done the change requests. Could you please review.

**Review by krystalcode — CHANGES_REQUESTED** [review]
Please make changes based on comments on #27

**Comment by safalliajoseph** [comment]
@krystalcode I have made changes as requested in #27. Please review

**Comment by krystalcode** [comment]
Merged on Drupal.org

**Pull request closed without merging**
